GNN_default_config = dict(
    actor_kwargs=dict(
        input_node_dim=4,
        input_edge_dim=1,
        feature_dim=128,
        log_std_min=-2,
        log_std_max=10,
        gnn_layer_kwargs=dict(
            node_dim=128,
            edge_dim=128,
            effect_processor_hidden_layers=[128],
            update_processor_hidden_layers=[128]
        ),
        pooling_layer_kwargs=dict(
            in_channels=128,
            ratio=0.8,
        ),
        num_gnn_layers=3
    ),

    critic_kwargs=dict(
        q_kwargs=dict(
            input_node_dim=4,
            input_edge_dim=1,
            feature_dim=128,
            gnn_layer_kwargs=dict(
                node_dim=128,
                edge_dim=128,
                effect_processor_hidden_layers=[128],
                update_processor_hidden_layers=[128]
            ),
            pooling_layer_kwargs=dict(
                in_channels=128,
                ratio=0.8,
            ),
            num_gnn_layers=3
        )
    )
)